### ISSUE TITLE
Organize music collection

### ISSUE THREAD

**Issue by JeanMRussell** [zippy/jungle-laser#5]
House appreciates organizing music collection.

![IMG_20200208_120428](https://user-images.githubusercontent.com/30393568/74107136-12df5000-4b3b-11ea-8120-eb52d24466b4.jpg)

**Comment by qubist** [comment]
**Remote knowledge contribution:** The records in the yellow milk crate are mine.

**Request:** I request that distinction is preserved. Please move them into my room if that aids the organization, or leave them out (ideal; folks should play them!) but separate from house's music.

**Comment by MorvinBear** [comment]
**Solution proposed by direct implementation with assumption through relationship that it will be acceptable, probably not upsetting, and in the event that it is, that it could easily be reversed:** The records have their own shelf, with labels for own/stewardship and indications for use.

![IMG_20200215_141715](https://user-images.githubusercontent.com/2879930/74595515-3c531c80-5010-11ea-8cbb-76fc65b29ada.jpg)

![IMG_20200215_143630](https://user-images.githubusercontent.com/2879930/74595518-407f3a00-5010-11ea-835d-71031f27f67c.jpg)


**Request:** @qubist, does this work for you? If yes, do you have preference for the yellow crate to stay in your room or in the basement? 

**[New issue raised:](https://github.com/zippy/jungle-laser/issues/5)** for @zippy to go through the unmusic-related books that were taking up the perfectly sized record-shelf on the music stand where otherwise everything is music related.

**Comment by qubist** [comment]
> does this work for you? If yes, do you have preference for the yellow crate to stay in your room or in the basement?

Yes! Worried people will put records back in the wrong spot, but that's ok. Crate can go in my room, as I may want to lug those records a few degrees around the globe at some point in the near future.

**Comment by MorvinBear** [comment]
also, @JeanMRussell I tidied the rest of the space up, I did not create a system for organizing any deeper than medium (cd's, casettes, records), but it looks way better. Closing out -
