### ISSUE TITLE
Add fireguard in basement

### ISSUE THREAD

**Issue by JeanMRussell** [zippy/jungle-laser#9]
House appreciates reducing fire risk by adding fire guard to top of basement section of chimney. 

This has already led to a burn in fabric and a mattress leaning against chimney base.

**Comment by MorvinBear** [comment]
There is a place where fire can get pooped out to light things on fire to light the house on fire. Art, Eric, and I blathered about it in the living room for a bit and argued about the situation until I got this repo open and Eric talked about cutting a grate out of sheet metal sugrued into space, which is elegant and cool, and also less likely to happen quick-easy. Art was proposing that we take a brick, bash it into the shape it needs to be, and then shove it right-the-fuck-into the spot that it would keep the fire from pooping out of the chimney and catching the house on fire, which, the house appreciates, because the house appreciates not being on fire except inside the fireplace and the stove. 

Action step: I'll get a brick, bash it into place and shove it in the slot.

**Comment by zippy** [comment]
WOOT!

**Comment by MorvinBear** [comment]
I went scavenging. I got bricks and metal grate to explore both. I made a fence, it didn't work well. I smashed a brick into the right shape, it didn't look good, and limited airflow. I combined the two and made a fence-brick. air flows through, and even if an ember makes it through one side of the brick, it's very unlikely to be big enough to make it through the second one. 
![IMG_20200215_135137](https://user-images.githubusercontent.com/2879930/74593662-9b5a6680-4ffb-11ea-8f94-97246de55181.jpg)
